### ISSUE TITLE
Fazer caso de uso

### ISSUE THREAD

**Issue by GabrielMiler** [Projetos-de-Extensao/PBE_24.2_8001_I_BrainBox#12]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alvesskaio** [comment]
https://jonh-carvalho.github.io/PBE_24.2_8001/modelagem/casosdeuso/

**Comment by alvesskaio** [comment]
Tulizar ferramenta no vscode PLANTUML

**Comment by alvesskaio** [comment]
Fazer caso de uso no miro e depois mandar para o codigo do projeto no vscode

**Comment by alvesskaio** [comment]
exemplo -https://jonh-carvalho.github.io/PBE_24.2_8001/modelagem/Casos%20de%20Uso/Exemplo%20Biblioteca%20Digital/
