### ISSUE TITLE
Fazer 5w2h da plataforma

### ISSUE THREAD

**Issue by GabrielMiler** [Projetos-de-Extensao/PBE_24.2_8001_I_BrainBox#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alvesskaio** [comment]
Fizemos o 5w2h da empresa, agora precisamos fazer o da nossa plataforma

**Comment by Maffezzoli** [comment]
Commit do 5W2H da plataforma feito na branch 'maffezzoli'. Diretório:
PBE_24.2_8001_I_BrainBox/tree/maffezzoli/docs/base/5w2h.md
